modules:
  - type: files
    files:
      - source: system
        destination: / # copies files/system/* (* means everything inside it) into your image's root folder /

  - type: dnf
    repos:
      files:
        - https://pkgs.tailscale.com/stable/fedora/tailscale.repo
      copr:
        - dejan/lazygit
    install:
      packages:
        - lazygit # From the dejan/lazygit copr
        - chezmoi
        - zsh
        - oh-my-posh
        - zoxide
        - uutils-coreutils
        - btrfsmaintenance
        - duperemove
        - yt-dlp
        - neovim
        - luarocks
        - clevis
        - clevis-luks
        - clevis-dracut
        - clevis-udisks2
        - clevis-systemd
        - gh
        - fping
        - fd-find
        - telnet
        - netcat
        - btop
        - gnupg2-scdaemon
        - wireshark-cli
        - nushell
        - tmux
        - udisks2 # Added so that fwupd works
        - tailscale
        - 7zip
        - 7zip-standalone-all
        - smartmontools

  - type: fonts
    fonts:
      nerd-fonts:
        - Hack
  - type: systemd
    system:
      enabled:
        - podman-auto-update.timer
        - btrfs-scrub.timer
        - sshd.service
    user:
      enabled:
        - podman-auto-update.timer
