modules:
  - type: files
    files:
      - source: system
        destination: / # copies files/system/* (* means everything inside it) into your image's root folder /

  - type: dnf
    repos:
      files:
        - tailscale.repo
        - atim-nushell.repo
      keys:
        - keys/tailscale-fedora-repo.gpg
        - keys/atim-nushell.gpg
    install:
      packages:
        - distrobox
        - chezmoi
        - zsh
        - oh-my-posh
        - zoxide
        - uutils-coreutils
        - btrfsmaintenance
        - minisign
        - duperemove
        - yt-dlp
        - neovim
        - luarocks
        - clevis
        - clevis-luks
        - clevis-dracut
        - clevis-udisks2
        - clevis-systemd
        - gh
        - fping
        - fd-find
        - telnet
        - netcat
        - btop
        - wireshark-cli
        - nushell
        - tmux
        - zram-generator-defaults
        - mkosi
        - tailscale
        - 7zip
        - 7zip-standalone-all
        - smartmontools
        - pam-u2f
        - pam_yubico
        - erofs-utils
        - just
        - qemu-kvm
        - edk2-ovmf
