modules:
  - type: files
    files:
      - source: system
        destination: / # copies files/system/* (* means everything inside it) into your image's root folder /

  - type: dnf
    repos:
      files:
        - tailscale.repo
        - gemfury-nushell.repo
      keys:
        - keys/tailscale-fedora-repo.gpg
        - keys/gemfury-nushell.key
    install:
      packages:
        - distrobox
        - chezmoi
        - zsh
        - oh-my-posh
        - zoxide
        - uutils-coreutils
        - btrfsmaintenance
        - minisign
        - duperemove
        - yt-dlp
        - neovim
        - luarocks
        - clevis
        - clevis-luks
        - clevis-dracut
        - clevis-udisks2
        - clevis-systemd
        - gh
        - fping
        - fd-find
        - telnet
        - netcat
        - btop
        - wireshark-cli
        - nushell
        - tmux
        - tailscale
        - 7zip
        - 7zip-standalone-all
        - smartmontools
        - pam-u2f
        - pam_yubico
        - erofs-utils
  - type: copy
    from: ghcr.io/rulentwave/gentoo-prefix-stage4@sha256:4a773111df8becda115eb18de88eb52157ac7bc53c2102d481d2e88ded1c0612
    src: /out/gentoo-prefix.raw
    dest: /usr/lib/extensions/
